# Follow the instructions on https://smee.io/ to create a new channel to
# port-forward webhooks for local development. Change this value 
SMEE_URL := https://smee.io/
WEBHOOK_SERVER_PORT := ${WEBHOOK_SERVER_PORT}

forward-webhook:
	smee --url $(SMEE_URL) --port 