title: |md
  # Architecture
|

GitHub: {
  shape: image
  icon: https://icons.terrastruct.com/dev%2Fgithub.svg
}

Users: {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F359-users.svg
}

GKE Autopilot: {
    Webhook Server: {
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
    }

    NATS Queue : {
        shape: image
        icon: ./img/nats.png
    }

    Clone Repo Scanner : {
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
    }

    Octokit API Scanner : {
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
    }

    Arangodb: {
        shape: image
        icon: ./img/arangodb.png 
    }

    Web Application: {
        shape: image
        icon: https://icons.terrastruct.com/dev%2Fdocker.svg
    }
}

# Webhook server registers with GitHub repos/organization for webhook events
GitHub -> GKE Autopilot.Webhook Server: Event Webhook

# Webhook server publishes events in NATS queue
GKE Autopilot.Webhook Server -> GKE Autopilot.NATS Queue: Publish Repo Events

# Scanners subscribe to certain repo events
GKE Autopilot.Clone Repo Scanner -> GKE Autopilot.NATS Queue: Subscribe to Repo Events
GKE Autopilot.Octokit API Scanner -> GKE Autopilot.NATS Queue: Subscribe to Repo Events

# Scanners write metrics of interest to ArangoDB.
GKE Autopilot.Clone Repo Scanner -> GKE Autopilot.Arangodb: Write Metrics
GKE Autopilot.Octokit API Scanner -> GKE Autopilot.Arangodb: Write Metrics

# Web application fetches data from arangodb and presents it on UI
GKE Autopilot.Web Application -> GKE Autopilot.Arangodb: Reads

# Users are served pages from web application
Users -> GKE Autopilot.Web Application: Visit